### ISSUE TITLE
Blank on mobile screen

### ISSUE THREAD

**Issue by daimagine** [nmn/react-infinity#12]
Hi again,

I found another problem in rendering on mobile screen with `320px width`. Somehow it doesnt show anything (blank).
I checked the style of `infinite-container` and I found the height attr is `NaN` :
```
<div class="infinite-container" style="height:NaNpx;width:100%;position:relative;" data-reactid=".0.0.3.0.1">
<span data-reactid=".0.0.3.0.1.0"></span>
</div>
```

Please help me figured this out since I dont have any clue of whats going on. And this is my gist:
`https://gist.github.com/daimagine/e5e11a3a85118f6b5d9c`

Thank you

**Comment by nmn** [comment]
The fact that you're seeing NaN is clearly a bug, as no matter what, that should never happen.
But still, try adding a mobileHeight prop while calling React-Infinity, that seems to be causing the issue:

```
<ReactInfinity
		      data={this.props.products}
		      elementWidth={300}
		      elementHeight={290}
			  justifyOnMobile={false} // pass true to switch to a list instead of a grid on mobile.
			  elementMobileWidth={400} // element width to use for mobile view when `justifyOnMobile === false`
                          elementMobileHeight={290}
		      margin={10}
		      align="left"
		      childComponent={React.createFactory(ProductItem)}
		      />
```

When in mobile mode, (which is just a width-based break point which defaults to 480, but you can customise) React-Infinity doesn't fallback to the elementHeight. So, you have to explicitly pass mobileHeight. This is not ideal, and I'll push a fix for it.

**Comment by daimagine** [comment]
Sorry for late response, adding mobile height fixed this issue.
Thanks again for your help.
