### ISSUE TITLE
Provide props to child elements

### ISSUE THREAD

**Issue by daimagine** [nmn/react-infinity#16]
Hi again,
Can I provide another props into child elements beside the array of items itself? Because I need to pass parent's state into child elements.

Regards,

**Comment by nmn** [comment]
Could you elaborate on what you want to do exactly?

**Comment by daimagine** [comment]
Let say I have ProductItem as child component. Basically, I will pass my products into data attribute on ReactInfinity like this:

```
<ReactInfinity
		      data={this.props.products}
		      elementWidth={300}
		      elementHeight={310}
		      margin={10}
		      childComponent={React.createFactory(ProductItem)}
		      />
```

But I have to pass another parameter to ProductItem as props. Let say, I want to give my ProductItem a props named user.

How do I achieve this?

**Comment by nmn** [comment]
Currently I would recommend mapping over the `this.props.product` to pass that in.

Option 2: I wouldn't recommend this as I will get rid of factories in the future, but `React.createFactory` just returns a function that accepts props and children. (In this case just props)

So you could pass a custom function as well:

```
var ProfuctItemFactory = React.createFactory(ProductItem)
function ProductItemWithUser(props, children){
  props.user = user
  return ProductItemFactory(props, children)
}
```

**Comment by daimagine** [comment]
Hi, thanks for your insight.
Unfortunately, the user prop is same for all product and I dont think it should mapped to `this.props.product`

Regarding your code sample, what is the children parameter? because I always get this error:
`Uncaught TypeError: this.props.childComponent is not a function`

Thank you.

**Comment by nmn** [comment]
In the code example, the children argument would always be undefined. I only left it there for clarity that it's a factory function.

In any case, you can use ProductItemWithUser as the factoryFunction value of `childComponent`

Makes sense?

**Comment by daimagine** [comment]
Im sorry I dont quite understand. Could you point out what is wrong instead?
I use code based on your example like this:
```
var defaultProps = { user: {id: 9999} }
var ProductItemFactory = React.createFactory(ProductItem)
function ProductItemWithProps(props, children){
  return ProductItemFactory(props, children)
}
```

and this is the react infinity component:

```
<ReactInfinity
              data={this.props.products}
              elementWidth={300}
              elementHeight={310}
              margin={10}
              childComponent={ProductItemWithProps(defaultProps)}
              />
```

above codes produce error 
`Uncaught TypeError: this.props.childComponent is not a function`

**Comment by nmn** [comment]
Try this:
```
var defaultProps = { user: {id: 9999} }
var ProductItemFactory = React.createFactory(ProductItem)
function ProductItemWithProps(commonProps){
  return function(props, children){
    return ProductItemFactory(Object.assign(commonProps, props), children)
  }
}
```

---
In your code, you were calling ProductItemWithProps before it was passed to ReactInfinity, hence ReactInfinity never got a factory function at all. Now, ProductItemWithProps returns a new factory function and so it should work.

**Comment by daimagine** [comment]
As always, works like a charm. Thank you for your awesome support and I will close this issue also
