### ISSUE TITLE
Allow specifying container other than window

### ISSUE THREAD

**Issue by cmwelsh** [nmn/react-infinity#8]
onResize: function () {
        this.setState({windowHeight: global.innerHeight, windowWidth: global.innerWidth});
      },

Currently the code in places such as above is assuming the user wants to render the component into the full width of the viewport.

Instead of calculating based on the window dimensions, it would enable more possibilities to allow users to supply a container. For example, the user might have a `max-width` set on their HTML template, or they might want to render the `react-infinite` component on just the right 50% of the page, etc.

**Comment by nmn** [comment]
I agree completely. I'm working to support this use-case on v2.0
I've just been very busy, so it's taking a little longer than expected. Will try to get it done soon.

**Comment by cmwelsh** [comment]
For my purposes I just hacked in an extra prop `containerWidth` and the parent of the `Infinite` component has some jQuery soup to measure itself and pass down the prop...
